name: Scan for secrets
on: push
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
       target: 'https://devsecops-appsec.github.io/react-project/'
