name: DAST Scan
on:
  pull_request:
jobs:
  hawkscan:
    name: DAST Scan 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.5.1
        with:
          token: ${{ secrets.ZAP_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://devsecops-appsec.github.io/react-project/'
          cmd_options: '-a'
         
