


      - name: trufflehog secret scanner 
        uses: trufflesecurity/trufflehog@v3.41.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
